# syntax=docker/dockerfile:1

FROM ubuntu:22.04

WORKDIR /mongo

RUN apt-get update && apt-get -y install gnupg curl systemctl && curl -fsSL https://pgp.mongodb.com/server-7.0.asc | \
    gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
    --dearmor && \
    echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list && \
    apt-get update && apt-get install -y mongodb-org


EXPOSE 27017

CMD ["systemctl", "start", "mongod"]
